import {
  FileClassification,
  GeneratedFileKind,
  listGeneratedFiles,
} from '@nx-plugin-openapi/core';
import { logger } from '@nx/devkit';

const CODE_FILE_PATTERN = /\.[mc]?[tj]sx?$/;

/** Top-level files of the hey-api output (`.gen` suffix optional). */
const TOP_LEVEL_KINDS: Record<string, GeneratedFileKind> = {
  types: 'model',
  schemas: 'model',
  zod: 'model',
  valibot: 'model',
  sdk: 'api',
  client: 'core',
  transformers: 'core',
  index: 'other',
};

/** Bundled runtime dirs of hey-api clients. */
const CORE_DIRS = ['client', 'core'];

function topLevelKind(path: string): GeneratedFileKind | undefined {
  const name = path.replace(CODE_FILE_PATTERN, '').replace(/\.gen$/, '');
  return TOP_LEVEL_KINDS[name];
}

function classifyFile(path: string): GeneratedFileKind {
  if (!CODE_FILE_PATTERN.test(path)) return 'other';
  const segments = path.split('/');
  if (segments.length === 1) return topLevelKind(path) ?? 'other';
  if (CORE_DIRS.includes(segments[0])) return 'core';
  // scoped plugin output, e.g. `@tanstack/react-query.gen.ts` wrapping the sdk
  return segments[0].startsWith('@') ? 'api' : 'other';
}

/**
 * Classifies @hey-api/openapi-ts output: `types.gen.ts` -> model,
 * `sdk.gen.ts` -> api, `client.gen.ts`, `client/**` and `core/**` -> core,
 * root `index.ts` (regenerated by post-processors) and the rest -> other.
 */
export function classifyHeyApiOutput(outDir: string): FileClassification {
  const files = Object.fromEntries(
    listGeneratedFiles(outDir).map((path) => [path, classifyFile(path)])
  );
  const unknown = Object.entries(files)
    .filter(([path, kind]) => kind === 'other' && CODE_FILE_PATTERN.test(path))
    .map(([path]) => path)
    .filter((path) => topLevelKind(path) !== 'other');
  if (unknown.length) {
    logger.warn(
      `hey-api: could not classify ${
        unknown.length
      } file(s), treating them as 'other': ${unknown.join(', ')}`
    );
  }
  return { files };
}
