export interface GenerateApiExecutorSchema {
  inputSpec: string | Record<string, string>;
  outputPath: string;
  configFile?: string;
  skipValidateSpec?: boolean;
  auth?: string;
  apiNameSuffix?: string;
  apiPackage?: string;
  artifactId?: string;
  artifactVersion?: string;
  dryRun?: boolean;
  enablePostProcessFile?: boolean;
  gitHost?: string;
  gitRepoId?: string;
  gitUserId?: string;
  globalProperties?: Record<string, string>;
  groupId?: string;
  httpUserAgent?: string;
  ignoreFileOverride?: string;
  inputSpecRootDirectory?: string;
  invokerPackage?: string;
  logToStderr?: boolean;
  minimalUpdate?: boolean;
  modelNamePrefix?: string;
  modelNameSuffix?: string;
  modelPackage?: string;
  packageName?: string;
  releaseNote?: string;
  removeOperationIdPrefix?: boolean;
  skipOverwrite?: boolean;
  skipOperationExample?: boolean;
  strictSpec?: boolean;
  templateDirectory?: string;
  generator?: string;
  autoInstall?: boolean;
  generatorOptions?: Record<string, unknown>;
}
