import { renderBarrel, selectBarrelModules } from './barrels';
import { ModuleExport } from './module-exports';

describe('barrels', () => {
  it('selects top-level, entry and cross-group imported modules', () => {
    const modules = selectBarrelModules({
      files: [
        'client/index.ts',
        'client/types.gen.ts',
        'core/types.gen.ts',
        'client.gen.ts',
        'core/README.md',
      ],
      importedWithinGroup: new Set([
        'client/index.ts',
        'client/types.gen.ts',
        'core/types.gen.ts',
      ]),
      importedFromOtherGroups: new Set(['client/index.ts']),
      starReExports: new Map(),
    });

    expect(modules).toEqual(['client.gen.ts', 'client/index.ts']);
  });

  it('skips cross-group imported modules already re-exported by an entry', () => {
    expect(
      selectBarrelModules({
        files: [
          'model/pet.ts',
          'model/models.ts',
          'model/tag.ts',
          'model/category.ts',
        ],
        importedWithinGroup: new Set([
          'model/pet.ts',
          'model/tag.ts',
          'model/category.ts',
        ]),
        importedFromOtherGroups: new Set(['model/tag.ts', 'model/category.ts']),
        // models -> pet -> tag; category only imported (not re-exported)
        starReExports: new Map([
          ['model/models.ts', ['model/pet.ts']],
          ['model/pet.ts', ['model/tag.ts']],
        ]),
      })
    ).toEqual(['model/category.ts', 'model/models.ts']);
  });

  it('renders export statements', () => {
    expect(
      renderBarrel(['configuration.ts', 'model/models.ts'], () => []).content
    ).toBe(
      `// Generated by the nx-plugin-openapi split post-processor. Do not edit.\n` +
        `export * from './configuration';\nexport * from './model/models';\n`
    );
  });

  it('re-exports by name without names clashing with earlier modules', () => {
    const exportsByModule: Record<string, ModuleExport[]> = {
      'client.gen.ts': [
        { name: 'client', key: 'client', isTypeOnly: false },
        { name: 'CreateClientConfig', key: 'cc-1', isTypeOnly: true },
      ],
      'client/index.ts': [
        { name: 'client', key: 'client', isTypeOnly: false },
        { name: 'createClient', key: 'create', isTypeOnly: false },
        { name: 'CreateClientConfig', key: 'cc-2', isTypeOnly: true },
        { name: 'Options', key: 'options', isTypeOnly: true },
      ],
    };

    const barrel = renderBarrel(
      ['client.gen.ts', 'client/index.ts'],
      (path) => exportsByModule[path]
    );

    expect(barrel.content).toContain(
      `export * from './client.gen';\n` +
        `export { createClient } from './client/index';\n` +
        `export type { Options } from './client/index';\n`
    );
    expect(barrel.shadowedExports).toEqual([
      'client/index.ts#CreateClientConfig',
    ]);
  });

  it('renders an empty module without exports', () => {
    expect(renderBarrel([], () => []).content).toMatch(/export \{\};\n$/);
  });
});
