import { ModuleExport, ModuleExportsResolver } from './module-exports';
import { isCodeFile, toModuleSpecifierPath } from './module-resolution';

export const BARREL_PATH = 'index.ts';

export interface BarrelInput {
  /** Files of one group, relative to the generated output dir (POSIX). */
  files: string[];
  /** Files of the group imported by other files of the same group. */
  importedWithinGroup: ReadonlySet<string>;
  /** Files of the group imported from other groups (must be reachable via alias). */
  importedFromOtherGroups: ReadonlySet<string>;
  /** Same-group `export * from` edges: file -> fully re-exported files. */
  starReExports: ReadonlyMap<string, readonly string[]>;
}

function isTopLevel(path: string): boolean {
  return !path.includes('/');
}

/** Modules whose exports are reachable through `export *` chains from `entries`. */
function collectReExported(
  entries: string[],
  starReExports: ReadonlyMap<string, readonly string[]>
): Set<string> {
  const reachable = new Set<string>(entries);
  const queue = [...entries];
  while (queue.length) {
    for (const target of starReExports.get(queue.shift() as string) ?? []) {
      if (!reachable.has(target)) {
        reachable.add(target);
        queue.push(target);
      }
    }
  }
  return reachable;
}

/**
 * Picks the modules re-exported by a lib barrel:
 * - top-level files of the generated output (e.g. `configuration.ts`)
 * - entry files no other file of the group imports (e.g. `model/models.ts`)
 * - files imported from other groups, unless an entry already re-exports
 *   them via `export *` (their imports now use the alias)
 *
 * Internal modules are not repeated, which keeps the barrel small and avoids
 * ambiguous `export *` names.
 */
export function selectBarrelModules(input: BarrelInput): string[] {
  const codeFiles = input.files.filter((path) => isCodeFile(path));
  const entries = codeFiles.filter(
    (path) => isTopLevel(path) || !input.importedWithinGroup.has(path)
  );
  const reachable = collectReExported(entries, input.starReExports);
  const unreachableImported = codeFiles.filter(
    (path) => input.importedFromOtherGroups.has(path) && !reachable.has(path)
  );
  return [...entries, ...unreachableImported].sort(compareModulePaths);
}

/** Top-level modules first, then alphabetical. */
function compareModulePaths(a: string, b: string): number {
  const depthDifference = a.split('/').length - b.split('/').length;
  return depthDifference || a.localeCompare(b);
}

export interface RenderedBarrel {
  content: string;
  /** `module#name` exports left out because an earlier module exports another binding under that name. */
  shadowedExports: string[];
}

function renderNamedExports(
  specifier: string,
  moduleExports: ModuleExport[]
): string[] {
  const values = moduleExports.filter((e) => !e.isTypeOnly).map((e) => e.name);
  const types = moduleExports.filter((e) => e.isTypeOnly).map((e) => e.name);
  return [
    ...(values.length
      ? [`export { ${values.join(', ')} } from '${specifier}';`]
      : []),
    ...(types.length
      ? [`export type { ${types.join(', ')} } from '${specifier}';`]
      : []),
  ];
}

/**
 * Renders `export * from` per module. If a module exports a name already
 * exported by an earlier module with a different binding (TS2308), it is
 * re-exported by name instead, without the clashing names: earlier modules
 * (top-level first) win.
 */
export function renderBarrel(
  modules: string[],
  exportsOf: ModuleExportsResolver
): RenderedBarrel {
  const header =
    '// Generated by the nx-plugin-openapi split post-processor. Do not edit.\n';
  if (!modules.length)
    return { content: `${header}export {};\n`, shadowedExports: [] };

  const exportedKeys = new Map<string, string>();
  const shadowedExports: string[] = [];
  const lines = modules.flatMap((path) => {
    const specifier = `./${toModuleSpecifierPath(path)}`;
    const moduleExports = exportsOf(path);
    const clashing = moduleExports.filter(
      (e) => exportedKeys.has(e.name) && exportedKeys.get(e.name) !== e.key
    );
    const fresh = moduleExports.filter((e) => !exportedKeys.has(e.name));
    fresh.forEach((e) => exportedKeys.set(e.name, e.key));
    if (!clashing.length) return [`export * from '${specifier}';`];
    clashing.forEach((e) => shadowedExports.push(`${path}#${e.name}`));
    return renderNamedExports(specifier, fresh);
  });
  return { content: `${header}${lines.join('\n')}\n`, shadowedExports };
}
